// <auto-generated />
using ACSBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ACSBackend.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240725181259_config")]
    partial class config
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ACSBackend.Database.Models.Config", b =>
                {
                    b.Property<string>("KEY")
                        .HasColumnType("text");

                    b.Property<string>("VALUE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KEY");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("ACSBackend.Database.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("ACSCardUID")
                        .HasColumnType("bytea");

                    b.Property<decimal?>("ACSPin")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("DiscordUserID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Permissions")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ID");

                    b.HasIndex("NameSurname");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
